if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("destiny")
BiocManager::install("ggplot")
BiocManager::install("patchwork")
BiocManager::install("plotly")
BiocManager::install("reticulate")
BiocManager::install("svglite")
BiocManager::install("scater")

library(reticulate)
reticulate::install_miniconda()
reticulate::conda_install('r-reticulate', 'python-kaleido')
reticulate::conda_install('r-reticulate', 'plotly', channel = 'plotly')
reticulate::use_miniconda('r-reticulate')
